version: "2"

plugins:
  nodesecurity:
    enabled: true
  git-legal:
   enabled: true
  fixme:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json
  duplication:
    enabled: true
    config:
        count_threshold: 2

exclude_patterns:
- config/**/*
- node_modules/**/*
- webpack.*.js
- karma.conf.js
- platforms/
- plugins/
- www/
- src/assets/*
- resources/*
- "**/*.spec.ts"
- "src/polyfills.ts"
- "src/app/entity/*"