sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=9e94eb42394f339fee6592314b209bd1afb92b11580fee8e550111aa42626990
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
services:
  - xvfb
branches:
  only:
    - master
dist: xenial
addons:
  chrome: stable
    
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      language: node_js
      node_js: "12.14.0"
        
      install:
        - npm install
        - npm install -g ionic cordova
        - ionic info
        
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: npm run test:onceAndCoverage
        
    - name: "E2E Tests"
      language: node_js
      node_js: "12.14.0"

      install:
        - npm install
        - npm install -g ionic cordova
        - ionic info
        
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script: npm run e2e

    - stage: "Build Android"
      language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3	
          - android-28
          - extra
          - extra-google-google_play_services
          
      before_install:
        - nvm install 12.14.0
      install:
        - npm install
        - npm install -g ionic cordova
        - npm install -g cordova-res
        - node --version
        - npm --version
        - gradle --version
        
      before_script:
        - ionic cordova resources android
        - ionic cordova platform add android
        - ionic info
      script: ionic cordova build android --prod

      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        file_glob: true
        file: "/home/travis/build/BenJneB/StudUCLouvain_ionic-v4/platforms/android/app/build/outputs/apk/*/*.apk"
        on:
          repo: BenJneB/StudUCLouvain_ionic-v4
          branch: master
       
    - stage: "Build iOS"
      os: osx
      language: objective-c
          
      before_install:
        - nvm install 12.14.0
      install:
        - npm install
        - npm install -g ionic cordova
        - npm install -g cordova-res
        - node --version
        - npm --version
        
      before_script:
        - ionic cordova resources ios
        - ionic cordova platform add ios
        - ionic info
      script: ionic cordova build ios --prod

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
