language: node_js
node_js: "11.13.0"
branches:
      only:
      - master
before_script:
      - npm update -g npm
      - npm install -g ionic cordova
script:
      - ionic cordova build browser --prod
deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN 
      keep-history: true
      on:
            branch: master
            local_dir: www
