env:
  global:
    - CC_TEST_REPORTER_ID=92d69553e067a327c9a402cd0b1b4e12d5bfdf8c48a7801e7ad6b41b920e9632
language: node_js
node_js: "10.7.0"
branches:
      only:
      - master
before_script:
      - npm install -g npm
      - npm install -g ionic
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
script:
      - ng build --prod
deploy:
      provider: app
      skip-cleanup: true
      github-token: $GITHUB_TOKEN 
      keep-history: true
      on:
            branch: master
            local_dir: www
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT