env:
  global:
    - CC_TEST_REPORTER_ID=92d69553e067a327c9a402cd0b1b4e12d5bfdf8c48a7801e7ad6b41b920e9632

language: node_js
node_js: "10.7.0"
addons:
  chrome: stable

branches:
      only:
      - master

before_script:
      #- npm install -g ionic
      - export CHROME_BIN=chromium-browser
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build

script:
      - ng test --watch=false --coverage

deploy:
      provider: app
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      keep-history: true
      on:
            branch: master
      local_dir: www

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT