env:
  global:
    - CC_TEST_REPORTER_ID=9e94eb42394f339fee6592314b209bd1afb92b11580fee8e550111aa42626990

language: node_js
node_js: "12.12.0"
dist: xenial
services:
  - xvfb
addons:
  chrome: stable

branches:
      only:
      - master

before_script:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: npm run test:onceAndCoverage
    - script: npm run e2e
      name: "E2E Tests"
    - script: ionic cordova build browser --prod
      before_script:
        - npm install -g ionic cordova
        - ionic cordova platform add browser
      name: "Build browser"
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
        local_dir: www

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

