env:
  global:
    - CC_TEST_REPORTER_ID=9e94eb42394f339fee6592314b209bd1afb92b11580fee8e550111aa42626990

language: node_js
node_js: "10.7.0"
addons:
  chrome: stable

branches:
      only:
      - master

before_script:
      - export CHROME_BIN=chromium-browser
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build

jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: npm run test:onceAndCoverage
    - script: npm run e2e
      name: "E2E Tests"     # names the second Tests stage job

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT